# fly.toml app configuration file generated for delivery-backend on 2023-08-08T23:53:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delivery-backend"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
